version: "3.9"

services:
  web:
    build: .
    container_name: web_server
    env_file:
      - path: ./dev.env
        required: true
      - path: ./prod
        required: false
    volumes:
      - ./logs:/var/log/nginx
      - ./index.html:/usr/share/nginx/html/index.html
      - ./site/404.html:/usr/share/nginx/html/404.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT}:80"   # HTTP
      - "${SSL_PORT}:443"  # HTT
    depends_on:
      - api
    environment:
      ENV: ${ENVIRONEMENT}

  api:
    image: clue/json-server
    restart: always
    container_name: api_server
    volumes:
      - ${DB_PATH}:/data/db.json
    environment:
      ENV: ${ENVIRONEMENT}
    ports:
      - "${API_PORT}:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3010:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
