global:
  scrape_interval: 10s  # Fréquence de collecte des métriques

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:2375']  # Récupère les métriques de l'API Docker
